{
 "title": "Python Runtime Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(app_python_version, job)"
    }
   },
   {
    "name": "pid",
    "query": {
     "query": "label_values(app_thread_count{}, pid)"
    }
   },
   { "name": "generation", "query": "0,1,2" }
  ]
 },
 "panels": [
  { "title": "操作系统与Python解释器", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "主进程运行时长(秒)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_os_uptime{worker_role=\"master\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python版本",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_python_version{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "worker进程数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(app_thread_count{worker_role=\"worker\", job=~\"$job\"}) by (pid))"
    }
   ]
  },
  {
   "title": "0代GC阈值对象个数",
   "type": "stat",
   "description": "Whenever the number of objects in generation 0 is greater than or equal to 700, trigger a generation 0 GC",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_gc_generation_threshold{generation=\"0\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "1代GC阈值次数",
   "type": "stat",
   "description": "Whenever Gen 0 triggers GC 10 times, Gen 1 triggers GC 1 time",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_gc_generation_threshold{generation=\"1\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "2代GC阈值次数",
   "type": "stat",
   "description": "Whenever the first generation triggers GC 10 times, the second generation triggers GC 1 time",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_gc_generation_threshold{generation=\"2\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "进程内存占用(字节)",
   "type": "timeseries",
   "description": "Bytes occupied by process memory",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "app_os_mem_rss{pid=~\"$pid\", job=~\"$job\"}",
     "legendFormat": "pid:{{pid}}"
    }
   ]
  },
  {
   "title": "进程CPU占用(百分比)",
   "type": "timeseries",
   "description": "Process CPU usage(percent)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "app_os_cpu_used_percent{pid=~\"$pid\", job=~\"$job\"}",
     "legendFormat": "pid:{{pid}}"
    }
   ]
  },
  {
   "title": "GC 每一代中的内存对象数",
   "type": "timeseries",
   "description": "Number of memory objects in each generation",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_gc_generation_object_count{pid=~\"$pid\",generation=~\"$generation\", job=~\"$job\"}",
     "legendFormat": "pid:{{pid}}-{{generation}}代"
    }
   ]
  },
  {
   "title": "进程持有的文件描述符数量",
   "type": "timeseries",
   "description": "Number of file descriptors held by the process(total)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "app_os_file_handles_num{pid=~\"$pid\", job=~\"$job\"}",
     "legendFormat": "pid:{{pid}}"
    }
   ]
  },
  {
   "title": "进程当前存在的线程数",
   "type": "timeseries",
   "description": "Number of threads held by the process",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "app_thread_count{pid=~\"$pid\", job=~\"$job\"}",
     "legendFormat": "pid:{{pid}}"
    }
   ]
  },
  { "title": "GC统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "GC内存代累计回收的次数",
   "type": "timeseries",
   "description": "is the number of times this generation was collected",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_gc_collections_stats_count{pid=~\"$pid\",generation=~\"$generation\", job=~\"$job\"}",
     "legendFormat": "pid:{{pid}}-{{generation}}代"
    }
   ]
  },
  {
   "title": "GC内存代累计回收的对象个数",
   "type": "timeseries",
   "description": "is the total number of objects collected inside this generation",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "app_gc_collected_stats_count{pid=~\"$pid\", generation=~\"$generation\", job=~\"$job\"}",
     "legendFormat": "pid:{{pid}}-{{generation}}代"
    }
   ]
  },
  {
   "title": "GC内存代累计不可回收的对象数",
   "type": "timeseries",
   "description": " is the total number of objects which were found to be uncollectable",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "app_gc_uncollectable_stats_count{pid=~\"$pid\",generation=~\"$generation\", job=~\"$job\"}",
     "legendFormat": "pid:{{pid}}-{{generation}}代"
    }
   ]
  }
 ]
}